import Head from "next/head";
import BooksList from "../components/BooksList";
import React, { useState, useEffect } from "react";
import { useStateContext } from "../components/StateContext";
import { FaFacebook, FaInstagram, FaYoutube, FaTwitter } from "react-icons/fa";

export default function Home() {
  const { searchValue, setSearchValue } = useStateContext();
  const [books, setBooks] = useState([]);

  const getBooks = async (searchValue) => {
    const res = await fetch(
      `https://www.googleapis.com/books/v1/volumes?q=${searchValue}`
    );
    const data = await res.json();
    if (data.items) setBooks(data.items);
  };

  useEffect(() => {
    getBooks(searchValue);
  }, [searchValue]);

  return (
    <div className="header">
      <Head>
        <title>Books Forest</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="heading">Books Forest</h1>

      <input
        className="searchbox"
        type="text"
        placeholder="Search any book....."
        onChange={(e) => setSearchValue(e.target.value)}
        value={searchValue}
      />

      <div>{searchValue && <BooksList books={books} />}</div>

      <div className="footer-container">
        <div className="social">
          <FaFacebook className="icon" />
          <FaInstagram className="icon" />
          <FaTwitter className="icon" />
          <FaYoutube className="icon" />
        </div>

        <h1>Copyright @ 2022 Salman Haider</h1>
      </div>
    </div>
  );
}
